### PR TITLE
Send Message to User

### PR DESCRIPTION
**Pull request by ahmedash95**
based on #2 , in this PR you can send a notification to user or twitter timeline 

``` php
return new TwitterMessage('ahmedash95','Test twitter laravel notification');
```

of course if you need to post it on timeline just use one parameter 

``` php
return new TwitterMessage('Test twitter laravel notification');
```

### CODE REVIEW

**Comment by christophrumpel** [comment]
Great and thx. I'm right now at the Laracon but I will try to check it out the next days.

**Comment by ahmedash95** [comment]
oh , have a nice time there , waiting your next response :)

**Comment by christophrumpel** [comment]
So finally I found some time =) First thx for the PR. I encountered an error due to the `count()` functions. You did the check like this `if(count($args == 2))` but it should be like `if(count($args) == 2)' . I changed that for me and then it worked. This is also why all the tests failed. Could you change that and update the PR?

Besides that I really like it =)

**Comment by christophrumpel** [comment]
And please take a look at the the styleci errors https://styleci.io/analyses/XaV0YY and change your code to that style.

**Comment by ahmedash95** [comment]
@christophrumpel i got shocked :D , don't know how `php if(count($args == 2))` worked with me before .. now everything is okay as i guess. 
PS . thanks for your nice words :)

**Comment by christophrumpel** [comment]
Thx @ahmedash95 . Everything is working now 👍

**Comment by ahmedash95** [comment]
😄  Thx @christophrumpel

**Pull request merged**
