### PR TITLE
Updated tweet length

### PR DESCRIPTION
**Pull request by gpluess**

### CODE REVIEW

**Comment by christophrumpel** [comment]
Hey @gpluess ,
Thx for the PR. I fixed some styles. Please update your PR with the latest master branch.

**Comment by gpluess** [comment]
Done! :)

**Comment by austinheap** [comment]
Any update on this?

**Comment by christophrumpel** [comment]
Thx for the reminder. Will test it right now.

**Comment by christophrumpel** [comment]
thx!

**Comment by austinheap** [comment]
@christophrumpel thank you sir!

**Pull request merged**
