### PR TITLE
Adding Laravel 6 support

### PR DESCRIPTION
**Pull request by jeffwa**
My first ever pull request. Removed support for older versions to get proper versions of laravel/framework and orchestra/testbench to install. Tests run fine.

### CODE REVIEW

**Comment by mydnic** [comment]
Much needed ! Hope this is merged soon :)

**Comment by christophrumpel** [comment]
Thanks for the PR. I made a new release and now waiting for Packagist.

**Comment by dneey** [comment]
Great! Just in time

**Comment by nickurt** [comment]
Looks like it's still not updated on packagist?, still getting ^2.1 ..

**Comment by christophrumpel** [comment]
Yeah, already sent @themsaid a message. He is the owner of the repo and needs to trigger it on the Packagist side.

**Pull request merged**
