### PR TITLE
migrating to V2 of twitter api

### PR DESCRIPTION
**Pull request by Nelwhix**
Fixing Issue #96

- post tweet route was changed from statuses/update to /tweets
- request body was changed from $body = ['status' => $this->getContent()]; to $body = ['text' => $this->getContent()];
- in_reply_to_status_id was changed to in_reply_to_tweet_id'
- TwitterMessage isJsonRequest is now true by default
- changed data format for attaching media with tweets

### CODE REVIEW

**Comment by christophrumpel** [comment]
Thx a lot, I will take a look today 👍

**Comment by christophrumpel** [comment]
Have you tried it with a Twitter app? The changes did not work for me. We might have to change authentication:

CleanShot 2023-07-06 at 09 58 59@2x

**Comment by Nelwhix** [comment]
> Have you tried it with a Twitter app? The changes did not work for me. We might have to change authentication:
> CleanShot 2023-07-06 at 09 58 59@2x

Are you trying to post a tweet on behalf of a user?.. because I just tried with success. I noticed that if you are posting a tweet to your own account it works, but if you are posting on behalf of a user we have to implement something called [3-step Oauth 1.0a](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/pin-based-oauth). Should I do that?

Screenshot (432)

**Comment by christophrumpel** [comment]
Thanks for the update, glad to know it works for you. Still not working on my side, but I now get a new error. I'm trying to send a tweet  for my own account, which owns the Twitter app. Did you had to set up "user authentication" for you app?

CleanShot 2023-07-09 at 13 45 44@2x

And I read that media endpoints do not work yet for V2? Can you maybe check if that is true? If yes, we might have to find a solution with V1.1 till that works. Thanks for the help

**Comment by Nelwhix** [comment]
> Thanks for the update, glad to know it works for you. Still not working on my side, but I now get a new error. I'm trying to send a tweet  for my own account, which owns the Twitter app. Did you had to set up "user authentication" for you app?
> 
> 
> 
> CleanShot 2023-07-09 at 13 45 44@2x
> 
> 
> 
> And I read that media endpoints do not work yet for V2? Can you maybe check if that is true? If yes, we might have to find a solution with V1.1 till that works. Thanks for the help

I think you have to follow this migration guide for your app [here](https://developer.twitter.com/en/docs/twitter-api/migrate/ready-to-migrate) . I also set up user authentication like so image

You are right media endpoints are not available on V2. So what I did in the TwitterChannel's send method was to wait till the media has been uploaded before switching to the V2 api and it works.

**Comment by Nelwhix** [comment]
@christophrumpel image Does your app fall under this. Elevated access gives you all V1 endpoints and some V2 endpoints that might be the issue

**Comment by christophrumpel** [comment]
Hey, thanks Ive seen that too today. That could have been, but v1.1 was also not working. I also tried now to create a new app and v2 is still not working. Maybe my whole account falls under this "elevated access"? Still, then at least v1 should work. This is quite a pain in the ass, especially because I'm sure I'm not the only one

**Comment by Nelwhix** [comment]
Maybe contact customer support and whatever they say can be part of the migration guide for the next release

**Comment by christophrumpel** [comment]
I've made it work to post a tweet with just the TwitterOAuth package after a million tries. But still not working on your PR, will give it a closer look to find the difference.

**Comment by Nelwhix** [comment]
Can you send your code snippet let me compare?

**Comment by christophrumpel** [comment]
That's how I made it work an hour ago:

image

BUT now after refreshing some key, it does NOT work like this anymore. It is really strange and definitely connected to the Twitter app. But before I know what it is, and make it work with the package as well, I cannot merge the PR. I hope I find the issue.

**Comment by Nelwhix** [comment]
@christophrumpel the tests are now passing, I tested with phpunit and my twitter app. What is remaining now is migrating direct messages to the new endpoint. Were you able to find what was wrong with the 'config' helper?

**Comment by christophrumpel** [comment]
Hey, yeah I was able to make it work with your branch. It seems the issues were indeed only on my side. So thanks for you work so far. I also tested media uploads and that also worked.

So `direct messages` is the only thing missing? Have figured out what we can do? Can I help somehow?

**Comment by christophrumpel** [comment]
I tried to give it a look, currently stuck at: https://github.com/laravel-notification-channels/twitter/blob/master/src/TwitterDirectMessage.php#L35

Where we try to get the users ID by screen name.

Got so far:

```php
$connection = new TwitterOAuth(
        config('services.twitter.consumer_key'),
        config('services.twitter.consumer_secret'),
        config('services.twitter.access_token'),
        config('services.twitter.access_token_secret')
    );

    $connection->setApiVersion('2');
    dd($connection->get("users/by/username/christophrumpel"));
```

image

**Comment by Nelwhix** [comment]
Yessss, that's where I got stuck too. And I can't find anywhere in the docs what access level is required for that endpoint. I will keep looking though

**Comment by christophrumpel** [comment]
Perfect, thx. We could also try to ship it without direct message support for now.

**Comment by christophrumpel** [comment]
Thanks a lot @Nelwhix 👏

**Pull request merged**
