### PR TITLE
TwitterImage class

### PR DESCRIPTION
**Pull request by ahmedash95**
Hi @christophrumpel , 

sorry for this long time delay. based on this issue #16 , now we can use twitter notification with **withImage()** method and give it an array of **TwitterImage** instances. please review it well because i don't know if it now clearly enough or I missed something
 ```php 
new TwitterStatusUpdate('Laravel notifications are awesome!')
        ->withImage([ new TwitterImage(public_path('uploads/images/ash.png')) ]) 
```

### CODE REVIEW

**Comment by christophrumpel** [comment]
Thx a lot@ahmedash95 ! I will check it out the next days.

**Comment by christophrumpel** [comment]
Hey @ahmedash95 , just looked over the code. I really like this adaption and think it is an improvement for the package. The only thing I don't like is that the method is singular (withImage) and the type is array. What about we make both possible: providing an array of TwitterImages or just one object. Fee like this would be very Laravel-like. What do you think?

**Comment by ahmedash95** [comment]
Yup , I'm totally agree with you . but i think laravel follow the singular way. 

what about using parameters ?

``` php
new TwitterStatusUpdate('Laravel notifications are awesome!')
       ->withImage( new TwitterImage(public_path('uploads/images/ash.png')) ) 

// for multiple images

new TwitterStatusUpdate('Laravel notifications are awesome!')
       ->withImage( 
            new TwitterImage(public_path('uploads/images/ash.png')) , 
            new TwitterImage(public_path('uploads/images/tayee.png'))  
        ) 

```

**Comment by christophrumpel** [comment]
Hm, let us first talk about the image object. I would prefer if the user doesn't need to know about it. What if we use that just internal and let the user provide the paths, something like that:

``` php
TwitterStatusUpdate('message')->withImage('full path to image'); 

TwitterStatusUpdate('message')->withImages([image1, image2]);
```

What do you think?

**Comment by ahmedash95** [comment]
Aha , got it now , it would be perfect

**Comment by ahmedash95** [comment]
@christophrumpel  now it accepts array or string 

``` php
TwitterStatusUpdate('message')->withImage('full path to image'); 

TwitterStatusUpdate('message')->withImages(['image1.png', 'image2.png']);
```

**Comment by christophrumpel** [comment]
Just looked through and I really like it! Just one small thing I noticed is that we don't have a test to make sure both string and array is working. We just have the test for the array "it_accepts_array_of_image_paths".

**Comment by ahmedash95** [comment]
@christophrumpel what about tests/TwitterChannelTest.php class ?

**Comment by christophrumpel** [comment]
Is it testet there?

I mean something like this? :

``` php
    /** @test */
    public function it_accepts_one_image_path()
    {
        $imagePath = 'path1';
        $message = (new TwitterStatusUpdate('myMessage'))->withImage($imagePath);
        $imagePathObject = collect($imagePath)->map(function($image){ return new TwitterImage($image); })->toArray();

        $this->assertEquals('myMessage', $message->getContent());
        $this->assertEquals($imagePathObject, $message->getImages());
    }
```

**Comment by ahmedash95** [comment]
@christophrumpel , sorry friend , I thought **TwitterChannelTest** used in tests but here's your implementation of one image test .

but what about ->getImages() method is it fine or change it to ->getImage() -- singular mood -- ?

**Comment by christophrumpel** [comment]
no problem! Thx a lot. Think we're ready =)

**Comment by ahmedash95** [comment]
@christophrumpel Great,  feel free to merge it now 😅

**Pull request merged**
