### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by Synchro**
Hi Christoph, here's a little PR with some simple cleanup, after you asked so nicely on Twitter. I noticed there's no code style config, and the formatting is a little inconsistent as a result – perhaps add a phpcs config?

I had a go at setting types on a few more things than I've submitted here, but for example `content` and `to` properties in `TwitterDirectMessage` look ideal candidates for constructor promotion, but it breaks horribly if you try, in particular because `to` may be an int, even though it's documented as a string.

### CODE REVIEW

**Comment by Synchro** [comment]
I don't understand the changes styleci is suggesting, they are very inconsistent! For example, suggesting:

```
-     * @param Notifiable $notifiable
+     * @param  Notifiable  $notifiable
```
at the same time as:

```
-     * @return  string
+     * @return string
```

even when there is nothing else to align with!

**Comment by Synchro** [comment]
Now I'm confused. I fixed all the things styleci flagged, and it's still reporting the same issues. I suspect many of these changes overlap with those in #79, but you can cherry pick as they are all separated.

**Comment by christophrumpel** [comment]
Hey Marcus, this is so nice of you, but there is already a PR by someone else an hour before yours 😬 Maybe we can add the things that are missing in the other PR on top from you. Sorry about that.

**Comment by christophrumpel** [comment]
I cherry-picked a few things, thanks a lot @Synchro for the help 👍

**Pull request closed without merging**
